---
tls_certs_certs:
  - ca_content: '{{ lookup("ansible.builtin.file", elasticsearch_ca_cert_path) }}'
    ca_key_content: '{{ lookup("ansible.builtin.file", elasticsearch_ca_key_path) }}'
    cert_path: '{{ elasticsearch_cert_path }}'
    key_path: '{{ elasticsearch_key_path }}'
  - ca_content: '{{ lookup("ansible.builtin.file", elasticsearch_transport_ca_cert_path) }}'
    ca_key_content: '{{ lookup("ansible.builtin.file", elasticsearch_transport_ca_key_path) }}'
    cert_path: '{{ elasticsearch_transport_cert_path }}'
    key_path: '{{ elasticsearch_transport_key_path }}'
...
