---
- name: Get elasticsearch health
  ansible.builtin.uri:
    url: "{{ opensearch_patterns_url }}/api/saved_objects/_find\
      ?fields=title&type=index-pattern"
    headers:
      osd-xsrf: osd-fetch
      securitytenant: Global
    user: '{{ opensearch_patterns_user }}'
    password: '{{ opensearch_patterns_password }}'
    force_basic_auth: true
  retries: 3
  delay: 30
  register: opensearch_patterns_result
...
